apiVersion: batch/v1
kind: Job
metadata:
  name: multi-completion-batch-job-with-parallelism
spec:
  completions: 6
  parallelism: 2
  template:
    metadata:
      labels:
        app: batch-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: main
        image: luksa/batch-job