apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubiads2
spec:
  selector:
    matchLabels:
      app: kubiads2
  template:
    metadata:
      labels:
        app: kubiads2
    spec:
      nodeSelector:
        disk: ssd
      containers:
      - name: main
        image: stv707/kubia:v14