apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-disk-11g
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 11Gi    