apiVersion: v1
kind: Pod
metadata:
  name: azure-app
spec:
      containers:
      - name: azure-app
        image: alpine
        volumeMounts:
          - name: my-data
            mountPath: /var/mydatabin
        command: ["/bin/sh"]
        args: ["-c", "while true; do date >> /var/mydatabin/azure-app.txt; sleep 20; echo azure-app>> /var/mydatabin/azure-app.txt; done"]
        ports:
        - containerPort: 7171
          protocol: TCP
      volumes:
        - name: my-data
          persistentVolumeClaim:
            claimName: azure-disk-2g