apiVersion: v1
kind: Pod
metadata:
  name: fortunepod
spec:
  containers:
  - image: stv707/fortune
    name: html-generator
    volumeMounts:
    - name: internalvolume
      mountPath: /var/htdocs
  - image: nginx:alpine
    name: nginx-webserver
    volumeMounts:
    - name: internalvolume
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: internalvolume
    emptyDir: {}