apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb1-pv
spec:
  capacity: 
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.240.0.6
    path: /export/
