apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfspv-15g
spec:
  capacity: 
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.240.0.6 # Change to vm001 NFS Private Address
    path: /export/