apiVersion: v1
kind: Pod
metadata:
  name: kubia-pod-init
  labels: 
    app: kubia-pod-init
spec:
  initContainers:
  - name: sleepy
    image: alpine
    command: ['sleep', '30']
    #command: ['exit', '25']
  containers:
  - image: stv707/kubia:v14
    name: kubia-pod-init
    ports:
    - containerPort: 8080
      protocol: TCP