apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kubiapet
spec:
  serviceName: kubiapet
  replicas: 2
  selector:
    matchLabels:
      app: kubiapet # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: kubiapet
    spec:
      containers:
      - name: kubiapet
        image: stv707/kubia-pet:v1
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: data
          mountPath: /var/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      resources:
        requests:
          storage: 1Gi
      accessModes:
      - ReadWriteOnce
      storageClassName: "default"
