apiVersion: v1
kind: ReplicationController
metadata:
  name: rodeo
  labels:
    app: rodeo
spec:
  replicas: 2
  selector:
    app: rodeo
  template:
    metadata:
      labels:
        app: rodeo
    spec:
      containers:
      - name: rodeo
        image: stv707/kubia:v14
        ports:
        - containerPort: 8080
          protocol: TCP